timescreen: Further long overdue cleanup, including:
* cursor invisibility
* trap ctrlC
* better centering (toilet does not center things like figlet could)
* improve groovybar and use tput generated cursor movement

diff --git a/timescreen b/timescreen
--- a/timescreen
+++ b/timescreen
@@ -20,6 +20,7 @@ LOLCAT=/usr/games/lolcat
 DATEFONT=thick		
 TIMEFONT=colossal	
 
+# personal changes to defaults (above) can be baked into a config file:
 RCFILE=$HOME/.timescreenrc
 
 
@@ -30,6 +31,18 @@ RCFILE=$HOME/.timescreenrc
 # there is nothing to set. The defaults are off, these switch them on. Sorry,
 # but at the moment, that's how it is. I can't be bothered setting it up better
 # ...besides, the default is the simplest. Cope. 
+
+tputsc=$(tput sc)   # save cursor
+tputel=$(tput el)   # clear line
+
+# restore cursor visibility on ^c exit
+trap ctrl_c INT
+function ctrl_c() {
+    echo ""
+    tput cnorm
+    tput cup $(tput lines) 0
+    exit 0
+}
 
 version="\
 timescreen, by Owen Cameron <nemo@net.house.cx>
@@ -47,7 +60,6 @@ Usage: timescreen [options] [--version] [--help]
 	  -d		(double-height second counter)
 	  -b		(turn on chimes)
 	  -f		(turn on fortunes) (every 7 minutes)
-	  -m		(turn on mail check) *every 3 minutes)
 	  -fn1=xxxx	(figlet font for date)
 	  -fn2=xxxx	(figlet font for time)
 	  -figbin=/path/to/figlet	(full command path to figlet)
@@ -58,7 +70,7 @@ Usage: timescreen [options] [--version] [--help]
 ** If -w is set, and the value is 95 or greater, then the default fonts become
 **	'roman' for the date, and 'doh' for the time. 
 ** The -fn1 and -fn2 settings have priority over both of these.
-** 'showfigfonts(6)'  will give you a runthrough of all your fonts
+** 'showfigfonts(6)' if installed will give you a runthrough of all your fonts
 "
 
 
@@ -87,10 +99,13 @@ do
 done
 
 
+# cursor invisible
+tput civis
+
+
 ## check for the existance of a config file, and if it exists, use it. 
-# this config file is simply a static list of hte settings you want... ;)
 if [ -x $RCFILE ]; then
-. $RCFILE
+  . $RCFILE
 fi
 
 
@@ -116,11 +131,21 @@ if [ "$WIDTH" -ge "95" ]; then
 fi  
 
 
+do_centered() {
+  export IFS=x
+  cat /dev/stdin | while read line ; do printf "%-$(( ($WIDTH-${#line})/2 -2 ))s %s\n" " "  "$line" ; done
+  unset IFS
+}
+
+# this simply prepends every line with a "clear line" control code
+do_refreshline() {
+    export IFS=x
+    cat /dev/stdin | while read line ; do echo "${tputel}${line}" ; done
+    unset IFS
+}
+
 groovybar () {
 
-
-# fudge an extra few seconds to ensure the scripted minute doesn't end too soon
-# ...it sucks when that happens!
 SEC_ELAPSED=$(date '+%-S')
 SEC_REMAINING=$((60-$SEC_ELAPSED))
 
@@ -128,45 +153,58 @@ tstamp=$(sleepenh 0)
 
 if [ "$DOSECONDS" = "yes" ]; then
   if [ "$WIDTH" -ge "125" ] ; then 
+    # Due to control chars in groovybar I can't use the do_centered kludge
+    # ...so this is the alternate kludge
     SPACES=$((($WIDTH-125)/2)) 
-    # Above centers the groovybar, but modern figlet doesn't center, so I limit the spacing thus: 
-    [ $SPACES -gt 10 ] && SPACES=10
+    tput el
     tput cuf ${SPACES}
-    echo -ne "-[\e[s        ..        ..        ||        ..        ..        ==        ..        ..        ||        ..        ..          ]-"
+    echo -ne "-[${tputsc}        ..        ..        ||        ..        ..        ==        ..        ..        ||        ..        ..          ]-"
     if [ "$TALLSECONDS" = "yes" ]; then
       echo ""
+      tput el
       tput cuf ${SPACES}
-      echo -ne "-[        ^^        ^^        ||        ^^        ^^        ==        ^^        ^^        ||        ^^        ^^          ]-"
+      echo "-[        ^^        ^^        ||        ^^        ^^        ==        ^^        ^^        ||        ^^        ^^          ]-"
     fi
 
   else
-    SPACES=$((($WIDTH-64)/2)) 
-    echo -ne "\e[${SPACES}C"
-    echo -n "-[" ; tput sc ; echo "    .    .    |    .    .    O    .    .    |    .    .     ]-"
+    tput el
+    tput cuf $(( (WIDTH-64)/2 ))
+    echo "-[${tputsc}    .    .    |    .    .    O    .    .    |    .    .     ]-"
     if [ "$TALLSECONDS" = "yes" ]; then
-      echo -ne "\e[${SPACES}C"
-      echo -ne "-[              |              O              |               ]-"
+      tput el
+      tput cuf $(( (WIDTH-64)/2 ))
+      echo "-[              |              O              |               ]-" 
     fi
   fi
 
   # anything below the groovybar, put it here now:
-  echo -e "\n\e[J"
-#  tail -5 $HOME/var/log/fmail.log | ccze -A
-  md-count | column | head -5 | ccze -A
+  echo "${tputel}"
+# sketches on a unicode groovybar
+#  echo "╓─▄───╥─────╖" | do_centered | do_refreshline
+#  echo "╙─▀───╨─────╜" | do_centered | do_refreshline
 
-  #echo -ne "\e[u"
-  tput rc
+
+# trailing info. fortune, or some kind of log check, etc
+  # 
+  if [ "$DOFORTUNE" = "yes" ] && [ $FORTCOUNT -ge 3 ]; then 
+#    tput ed
+    /usr/games/fortune -s | do_centered | $LOLCAT -f |  do_refreshline
+    FORTCOUNT=0
+  else
+    md-count | column -c $WIDTH | head -n 5 | ccze -A | do_refreshline
+  fi
+  tput ed # and clear any remaining cruft
+
+  tput rc # go back to the groovybar and draw in the seconds
 
   # so now we tell the groovybar to catch up those seconds...
   if [ "$TALLSECONDS" = "yes" ]; then
     if [ "$WIDTH" -ge "125" ] ; then
-      for i in `seq 1 "$SEC_ELAPSED"` ; do
-        # echo -ne "##\e[2D\e[1B##\e[1A"
+      for i in $(seq 1 "$SEC_ELAPSED") ; do
         echo -n "##" ; tput cub 2 ; tput cud 1 ; echo -n "##" ; tput cuu 1
       done
     else
-      for i in `seq 1 "$SEC_ELAPSED"` ; do
-        # echo -ne "#\e[1D\e[1B#\e[1A"
+      for i in $(seq 1 "$SEC_ELAPSED") ; do
         echo -n "#" ; tput cub 1 ; tput cud 1 ; echo -n "#" ; tput cuu 1 
       done
     fi
@@ -185,26 +223,24 @@ if [ "$DOSECONDS" = "yes" ]; then
   # and now print each remaining second, in turn, as it needs to be
   if [ "$TALLSECONDS" = "yes" ]; then
     if [ "$WIDTH" -ge "125" ] ; then
-      for i in `seq 1 "$SEC_REMAINING"` ; do
+      for i in $(seq 1 "$SEC_REMAINING") ; do
         tstamp=$(sleepenh $tstamp 1.0)
-        #echo -ne "##\e[2D\e[1B##\e[1A"
         echo -n "##" ; tput cub 2 ; tput cud 1 ; echo -n "##" ; tput cuu 1
       done
     else
-      for i in `seq 1 "$SEC_REMAINING"` ; do
+      for i in $(seq 1 "$SEC_REMAINING") ; do
         tstamp=$(sleepenh $tstamp 1.0)
-        #echo -ne "#\e[1D\e[1B#\e[1A"
         echo -n "#" ; tput cub 1 ; tput cud 1 ; echo -n "#" ; tput cuu 1 
       done
     fi
   else
     if [ "$WIDTH" -ge "125" ] ; then
-      for i in `seq 1 "$SEC_REMAINING"` ; do
+      for i in $(seq 1 "$SEC_REMAINING") ; do
         tstamp=$(sleepenh $tstamp 1.0)
         echo -ne "##"
       done
     else
-      for i in `seq 1 "$SEC_REMAINING"` ; do
+      for i in $(seq 1 "$SEC_REMAINING") ; do
         tstamp=$(sleepenh $tstamp 1.0)
         echo -ne "#"
       done
@@ -215,76 +251,53 @@ else
 fi 
 }
 
-
-
 # loop continuous and give us output!
 while true ; do
-  # clear
-  # instead of clearing the screen, we just move the cursor back to the top
-  # and go again.
-  # we SHOULD do some checking here for fortune... since if a fortune is about
-  # to be used, this will make things look wierd. 
 
   if [ "$DOLOOP" = "yes" ] ; then
-    #echo -ne "\e[1;1f"     # reset the cursor to the topleft :)
-    #echo -ne "\e[2K"    # erase this first line. 
     tput cup 0 0    # cursor to topleft
-    tput el         # erase line
   fi
 
   if [ "$CLEARSCREEN" = "yes" ] ; then
-#    echo -ne "\e[2J"     # clear the screen
-     tput clear
+    tput clear
     CLEARSCREEN="no"
   fi
   
-  echo " "
-  $FIGBIN -f term -W -w "$WIDTH" "        "`uptime`
-  echo ""
-#  myinternode.sh 
-#   echo ""
-#   $FIGBIN -f term -W -w "$WIDTH" `date '+%a %e %b %H:%M:%S %Z %Y'`
-#   date +'%Y-%m-%d %T'    # ISO date/time format
-  echo " "
-  # we do a fortune every 7 instances. (used to be random)
-  if [ $FORTCOUNT -eq "7" ] && [ "$DOFORTUNE" = "yes" ] ; then 
-    echo -ne "\e[J"     # clear the screen below cursor 
-    /usr/games/fortune -a
-    echo " "
-    echo " "
-    CLEARSCREEN="yes"
-    FORTCOUNT=0
-  else
-    $FIGBIN -d $FIGDIR -f $DATEFONT -w "$WIDTH" " "`date '+%a %-d %b'` | $LOLCAT
-    echo -en "\e[1m"
-    $FIGBIN -d $FIGDIR -f $TIMEFONT -w "$WIDTH" "     "`date '+%H : %M'`" " | $LOLCAT
-    echo -en "\e[0m"
-    FORTCOUNT=$(($FORTCOUNT+1))
-  fi
+  echo "${tputel}"
+#  echo " columns: $COLUMNS, width: $WIDTH, tput cols: $(tput cols)"
+  uptime | do_centered | do_refreshline
+  echo "${tputel}"
+
+# display the date and time! important stuff!!
+  $FIGBIN -d $FIGDIR -f $DATEFONT -w $WIDTH -W "$(date '+%a %-d %b')" | do_centered | $LOLCAT -f | do_refreshline
+  echo -en "\e[1m"
+  $FIGBIN -d $FIGDIR -f $TIMEFONT -w $WIDTH -W "$(date '+%H:%M')" | do_centered | $LOLCAT -f | do_refreshline
+  echo -en "\e[0m"
+  FORTCOUNT=$(($FORTCOUNT+1))
 
   # if it's on the hour, beep a few times as appropriate 
-  if [ `date '+%M'` -eq "00" ]; then
-    # clear the second counting bar specificaly here since otherwise it's
-    # missplaced compared to normal... 
-    echo -ne "\e[J"     # clear the screen below cursor 
+  if [ $(date '+%M') -eq "00" ]; then
     OCLOCK=`date '+%l'`
-    # sleep a few seconds here to allow the rendering of the time to catch up
+    # sleep a moment here to allow the rendering of the time to catch up
     # on slow terminals. elsewise we lose each distinctive beep.
     # Originally 5 seconds. Making it 1 here in the 2020s
     sleep 1
     if [ "$DOBEEP" = "yes" ]; then
-      for a in `seq 1 $OCLOCK` ; do
-        echo -en "$a . \a\a\a"
+      echo -n "${tputel}"
+      for a in $(seq 1 $OCLOCK) ; do
+        echo -en "$a|\a\a\a"
         sleep 1
       done
     fi
-    echo "It's $OCLOCK O'Clock and all's well!"
-    echo " "
-    CLEARSCREEN="yes"
+    echo "It's $OCLOCK O'Clock and all's well!" 
+    echo "${tputel}"
+    # CLEARSCREEN="yes"
   fi
   if [ "$DOLOOP" = "no" ]; then
-    exit 0
+    ctrl_c  # this handles our cleanup
   fi 
   groovybar
 done
-exit 0
+
+# this should never be reached
+exit 1
